from typing import Any, Dict, List, Optional, Tuple

class Policy:
    def __init__(self, fuel: int = 500_000) -> None: ...
    def set_env(self, key: str, value: str) -> None: ...
    def allow_url(self, prefix: str) -> None: ...
    def __repr__(self) -> str: ...

class Sandbox:
    def __init__(self, wasm_path: str, policy: Policy) -> None: ...
    def init(self, message: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def tick(self) -> Optional[Dict[str, Any]]: ...
    def run(
        self, init_message: Dict[str, Any], max_ticks: int = 100
    ) -> List[Dict[str, Any]]: ...
    def stats(self) -> Dict[str, Any]: ...
    def __enter__(self) -> Sandbox: ...
    def __exit__(self, *exc: Any) -> None: ...

class RoundSummary:
    messages_routed: int
    messages_dropped: int
    messages_dlq: int
    dlq_depth: int
    routing_topology: str
    round_fuel: int
    crashed: List[str]
    agent_inbox_depths: Dict[str, int]
    observed_messages: List[str]
    def __repr__(self) -> str: ...

class Orchestrator:
    def __init__(
        self,
        topology: Optional[str] = None,
        hub: Optional[str] = None,
        dlq_enabled: Optional[bool] = None,
    ) -> None: ...
    def spawn(self, agent_id: str, wasm_path: str) -> None: ...
    def kill(self, agent_id: str) -> None: ...
    def pause(self, agent_id: str) -> None: ...
    def resume(self, agent_id: str) -> None: ...
    def tick_agent(self, agent_id: str) -> None: ...
    def tick_all(self) -> RoundSummary: ...
    def agent_status(self, agent_id: str) -> str: ...
    def agent_count(self) -> int: ...
    def list_agents(self) -> List[Tuple[str, str]]: ...
    def save(self, path: str) -> None: ...
    def save_full(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> Orchestrator: ...
    def export_summary(self) -> str: ...
    def set_save_every(self, n: int) -> None: ...
    def set_checkpoint_dir(self, dir: str) -> None: ...
    def __repr__(self) -> str: ...
